---
title: "mean under stochastic intervention"
author: "Jonathan Levy"
date: "Thursday, July 16, 2015"
output: word_document
---
#This file has no changes
```{r echo=FALSE, warning=FALSE,message=FALSE}
library(tmle)
library(foreach)
library(doSNOW)
library(origami)
library(glmnet)
library(ggplot2)
library(plyr)
library(dplyr)
registerDoSNOW(makeCluster(4, type = "SOCK"))
  
logit = function(x) qlogis(x)
inv.logit= function(x) plogis(x)



fluctuate=function(tmledata,flucmod,subset=seq_len(nrow(tmledata))){
  suppressWarnings({fluc=glm(flucmod, data=tmledata[subset,],family = "binomial")})
  list(eps=coef(fluc))
# summary(fluc)
}

Qbar0 <- function(A, W) {
    
    W1 <- W[, 1]
    W2 <- W[, 2]
    W3 <- W[, 3]
    W4 <- W[, 4]
    Qbar <- plogis(ifelse(W4 > 0, 1 - W1^2 + 3 * W2 + (A==1) * (5 * W3^2 - 4.45) + (A==2), 
                           -0.5 - W3 + 2 * W1 * W2 + (A==1) * (3 * abs(W2) - 1.5) + 5 * (A==3) * W3))
    return(Qbar)
}

g0 <- function(W) {
    W1 <- W[, 1]
    W2 <- W[, 2]
    W3 <- W[, 3]
    W4 <- W[, 4]
    
    # rep(0.5, nrow(W))
    A1 <- plogis(W1 - W2)
    A2 <- plogis(W2 - W1)
    A3 <- plogis(W2 - W3)
    A <- cbind(A1, A2, A3)
    
    # make sure A sums to 1
    A <- t(apply(A, 1, function(x) x/sum(x)))
}

gen_data <- function(n = 1000, p = 4) {
    W <- matrix(rnorm(n * p), nrow = n)
    colnames(W) <- paste("W", seq_len(p), sep = "")
    pA <- g0(W)
    A <- factor(apply(pA, 1, function(pAi) which(rmultinom(1, 1, pAi) == 1)))
    A_vals <- levels(A)
    #A <- t(apply(pA, 1, function(pAi) rmultinom(1, 1, pAi) == 1))
    u <- runif(n)
    Y <- as.numeric(u < Qbar0(A, W))
    Ya=sapply(A_vals,Qbar0,W)
    d0 <- apply(Ya,1,which.max)
    Yd0 <- as.numeric(u < Qbar0(d0, W))
    data.frame(W, A, Y,Ya=Ya, d0,Yd0)
}

data <- gen_data(1000, 5)

Anode <- "A"
Wnodes <- grep("^W", names(data), value = T)
# Q_library <- c("SL.glm", "SL.glmem", "SL.glmnetprob", "SL.step.forward", "SL.gam", 
#     "SL.rpart", "SL.rpartPrune", "SL.mean")
Q_library <- c("SL.glm","SL.step.forward", "SL.gam","SL.rpart", "SL.rpartPrune", "SL.mean")
Q_fit=origami_SuperLearner(data$Y,data[,c("A",Wnodes)],SL.library=Q_library,family=binomial())
# Q_fit=glm(Y~A+W1,data=data,family=binomial(link="logit"))
g_fit=multinomial_SuperLearner(data$A,data[,Wnodes])

A_vals=sort(unique(data$A))

Q_a <- sapply(A_vals, function(A_val) {
    newdata <- data[, c(Anode, Wnodes)]
    newdata[, Anode] <- A_vals[1]
    predict(Q_fit, newdata)$pred
})

pA=predict(g_fit,newdata=data[,Wnodes])$pred



